account_id = "39e0b7720b49a1fa6796546ba7b68d58"
name = "twitodon"
type = "webpack"
workers_dev = true
site = { bucket = "./public" }
compatibility_date = "2022-04-28"
kv_namespaces = [
    { binding = "TWITTER_TO_MASTODON_USERMAP", id = "e09c82417eac4f3082e706348f9366fa", preview_id = "33f1370672674c3e9821f80557842f95" }
]